project:
  name: quickstart-cribl-stream-privatelink-ami
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
    - us-east-1
  parameters: 
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3BucketName: $[taskcat_autobucket]
tests:
  cribl-deploy-new-vpc-arm-main:
    parameters: 
      AvailabilityZones: $[taskcat_getaz_2]
    template: templates/free_arm64_main.template.yaml
    regions:
      - us-east-1
  # cribl-deploy-new-vpc-arm:
  #   parameters: 
  #     AvailabilityZones: $[taskcat_getaz_2]
  #     VPCCIDR: 10.0.0.0/16
  #     PublicSubnet1CIDR: 10.0.128.0/20
  #     PublicSubnet2CIDR: 10.0.144.0/20
  #     PrivateSubnet1CIDR: 10.0.0.0/19
  #     PrivateSubnet2CIDR: 10.0.32.0/19
  #     VPCTenancy: default
  #     QSS3BucketRegion: $[taskcat_current_region]
  #   template: templates/free_arm64.template.yaml
  #   regions:
  #     - us-east-1
  # cribl-deploy-new-vpc-logging-arm:
  #   parameters: 
  #     AvailabilityZones: $[taskcat_getaz_2]
  #     VPCCIDR: 10.0.0.0/16
  #     PublicSubnet1CIDR: 10.0.128.0/20
  #     PublicSubnet2CIDR: 10.0.144.0/20
  #     PrivateSubnet1CIDR: 10.0.0.0/19
  #     PrivateSubnet2CIDR: 10.0.32.0/19
  #     VPCTenancy: default
  #     QSS3BucketRegion: $[taskcat_current_region]
  #     LogFilePrefix: cribl-vpc-logs
  #     TrafficType: ALL
  #     SQS: cribl-sqs-vpc-logs-arm
  #   template: templates/free_arm64.template.yaml
  #   regions:
  #     - us-east-1
  cribl-deploy-new-vpc-x86-main:
    parameters: 
      AvailabilityZones: $[taskcat_getaz_2]
    template: templates/free_x86_64_main.template.yaml
    regions:
      - us-east-1
  # cribl-deploy-new-vpc-x86:
  #   parameters: 
  #     AvailabilityZones: $[taskcat_getaz_2]
  #     VPCCIDR: 10.0.0.0/16
  #     PublicSubnet1CIDR: 10.0.128.0/20
  #     PublicSubnet2CIDR: 10.0.144.0/20
  #     PrivateSubnet1CIDR: 10.0.0.0/19
  #     PrivateSubnet2CIDR: 10.0.32.0/19
  #     VPCTenancy: default
  #     QSS3BucketRegion: $[taskcat_current_region]
  #   template: templates/free_x86_64.template.yaml
  #   regions:
  #     - us-east-1
  # cribl-deploy-new-vpc-logging-x86:
  #   parameters: 
  #     AvailabilityZones: $[taskcat_getaz_2]
  #     VPCCIDR: 10.0.0.0/16
  #     PublicSubnet1CIDR: 10.0.128.0/20
  #     PublicSubnet2CIDR: 10.0.144.0/20
  #     PrivateSubnet1CIDR: 10.0.0.0/19
  #     PrivateSubnet2CIDR: 10.0.32.0/19
  #     VPCTenancy: default
  #     QSS3BucketRegion: $[taskcat_current_region]
  #     LogFilePrefix: cribl-vpc-logs
  #     TrafficType: ALL
  #     SQS: cribl-sqs-vpc-logs-x86
  #   template: templates/free_x86_64.template.yaml
  #   regions:
  #     - us-east-1
