project:
  name: quickstart-cribl-stream-privatelink-ami
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
    - us-east-1
  parameters: 
      QSS3BucketName: "$[taskcat_autobucket]"
      QSS3BucketRegion: "$[taskcat_current_region]"
      webAccessCidr: 0.0.0.0/0
tests:
  cribl-deploy-new-vpc-arm-main:
    parameters: 
      AvailabilityZones: $[taskcat_getaz_2]
    template: templates/free_arm64_main.template.yaml
    regions:
      - us-east-1
  cribl-deploy-new-vpc-x86-main:
    parameters: 
      AvailabilityZones: $[taskcat_getaz_2]
    template: templates/free_x86_64_main.template.yaml
    regions:
      - us-east-2 